Assignment
downback/blog_api pull request #3
Opened 2024-01-25 21:42 UTC by downback

assignments from 23.1
1. hooks
2. for loop -> Array.from
3. ESlint & prettier setting
4. create new branch(assignment)

2024-01-26 15:03 UTC, humonnom requested changes
리뷰드렸습니다! @downback 
메인이랑 컨플릭이 나고 있는데 가능하면 컨플릭 먼저 해결해주세요.

2024-01-26 15:03 UTC, humonnom commented on package.json
> +    "eslint-plugin-prettier": "^7.33.2"
eslint-plugin-prettier 위치가 잘못된 것 같은데 확인 해보시겠어요?

2024-01-26 15:03 UTC, humonnom commented on src/pages/AddEditBlog.jsx
> +export default AddEditBlog
이 페이지 컴포넌트는 어떤 역할을 하나요? Add와 Edit라는 동사가 두개 들어가 있어서 어떤 의미인지 잘 모르겠어요. 가능한 명료하게 표현해주세요.

2024-01-26 15:03 UTC, humonnom commented on src/pages/Blog.jsx
> +      {/*<h1>{data.posts.title}</h1>*/}
이 부분은 데이터 가져오는 것이 아직 마무리가 안된 것 일까요?🧐

2024-01-26 15:03 UTC, humonnom commented on src/pages/Blog.jsx
> +export default Blog
컴포넌트 이름으로 Blog는 너무 추상적입니다. BlogDetailePage나 BlogDetail은 어떤가요?

2024-01-26 15:03 UTC, humonnom commented on src/pages/Home.jsx
> +export default Home
Home 컴포넌트도 사실은 블로그 포스트 리스트를 보여주는 역할을 하고 있습니다. BlogPosts나 BlogList가 한번에 이해하기 쉬울 것 같습니다.

2024-01-26 17:56 UTC, downback commented on src/pages/Blog.jsx
> +export default Blog
🫡

2024-01-26 17:58 UTC, downback commented on src/pages/Home.jsx
> +export default Home
BlogHome 은 어떨까요..? Blog / Post 가 들어가는 컴포넌트나 페이지들이 너무 많아서 뭔가... home 이 들어가야 안정감이....허허

2024-01-26 17:58 UTC, downback commented on package.json
> +    "eslint-plugin-prettier": "^7.33.2"
🫡

2024-01-27 04:33 UTC, humonnom commented on src/pages/Home.jsx
> +export default Home
네 BlogHome 좋습니다!

2024-01-27 08:45 UTC, merged