Assignment4
downback/blog_api pull request #9
Opened 2024-02-13 19:05 UTC by downback

- AddBlog & EditBlog pages 벨리데이션 작업
 버튼 누르면 validation 되도록
 에러 발생하면 submit 버튼disabled 처리

- 게시글 삭제 기능
 x 버튼 API 연동

2024-02-14 05:43 UTC, humonnom requested changes

2024-02-14 05:43 UTC, humonnom commented on src/pages/BlogDetail.jsx
> +      .delete(`https://dummyjson.com/posts/${id}`, singleBlog)
모든 API 요청은 hook 사용하도록 해주세요
✅ 일관성 유지하기

2024-02-14 05:43 UTC, humonnom commented on src/pages/EditBlog.jsx
> +        // navigate(`/post/${id}`)
쓸모없는 주석은 삭제해주세요.
✅ 주석은 정말 필요한 것만 남기기

2024-02-14 05:43 UTC, humonnom commented on src/pages/EditBlog.jsx
> +    // const error = validate(newPost)
마찬가지로 쓸모없는 주석은 삭제해주세요.

2024-02-14 14:00 UTC, downback commented on src/pages/EditBlog.jsx
> +    // const error = validate(newPost)
혹시 validation 로직 다르게 해볼때 필요할까봐 남겨둔 코드에여..!

2024-02-14 14:00 UTC, downback commented on src/pages/EditBlog.jsx
> +        // navigate(`/post/${id}`)
혹시 validation 로직 다르게 해볼때 필요할까봐 남겨둔 코드에여..!22

2024-02-14 14:01 UTC, downback commented on src/pages/BlogDetail.jsx
> +      .delete(`https://dummyjson.com/posts/${id}`, singleBlog)
근데 addblog / editblog 페이지에서도 put, post 다 해당 컨포넌트에서 했었는데...? 여기서 어떤 hook을 사용하라는건지 이해하지 못햇습니다ㅠ

2024-02-14 14:13 UTC, humonnom commented on src/pages/EditBlog.jsx
> +        // navigate(`/post/${id}`)
그런 것들은 해당 주석을 왜 남겼는지에 대한 내용도 같이 남겨주시고, 나머지 필요없는 주석은 삭제해서 최대한 주석 줄여주세요.


(아래는 예시)
// NOTE: 로직 미정(추후 확정 후 삭제예정)

2024-02-14 14:15 UTC, humonnom commented on src/pages/BlogDetail.jsx
> +      .delete(`https://dummyjson.com/posts/${id}`, singleBlog)
useGetPostList만들었던 것 처럼 커스텀 훅 만들어서 파일 따로 빼주세요!

2024-02-16 23:24 UTC, downback reviewed
input validation changed

2024-02-16 23:28 UTC, closed without merging